import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { createHash } from "node:crypto";
import { mkdir, open, readFile, realpath, rm, stat } from "node:fs/promises";
import { homedir, userInfo } from "node:os";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const execute = promisify(execFile);
const cliPath = fileURLToPath(new URL("cli.mjs", import.meta.url));
export async function runSystemCommand(command, args) {
  try {
    let env = process.env;
    // Trasporto del gestore systemd utente, non configurazione del bot.
    // Funziona anche da terminali/processi senza ambiente di login.
    if (command === "systemctl" && process.platform === "linux") {
      const uid = process.getuid();
      const runtime = `/run/user/${uid}`;
      const info = await stat(runtime);
      if (!info.isDirectory() || info.uid !== uid || (info.mode & 0o077) !== 0) throw new Error();
      env = { ...process.env, XDG_RUNTIME_DIR: runtime, DBUS_SESSION_BUS_ADDRESS: `unix:path=${runtime}/bus`, XDG_CONFIG_HOME: join(homedir(), ".config") };
    }
    const { stdout } = await execute(command, args, { timeout: 20000, maxBuffer: 65536, encoding: "utf8", env });
    return stdout.trim();
  } catch { throw new Error("Servizio systemd: comando fallito; verificare il gestore utente e consultare journalctl --user"); }
}

function quote(path) {
  if (!isAbsolute(path) || /[\x00-\x1f\x7f]/.test(path)) throw new Error("Servizio systemd: percorso assoluto senza caratteri di controllo richiesto");
  return `"${path.replaceAll("\\", "\\\\").replaceAll('"', '\\"').replaceAll("%", "%%")}"`;
}

function workingPath(path) {
  quote(path); // Stessa validazione, ma WorkingDirectory non accetta virgolette.
  if (path !== path.trim() || path.endsWith("\\")) throw new Error("Servizio systemd: directory di lavoro non rappresentabile");
  return path.replaceAll("%", "%%");
}

export function unitLocation(config, { home = homedir() } = {}) {
  const defaultFile = resolve(home, ".pi/communication/config.json");
  const suffix = config.configFile === defaultFile ? "" : `-${createHash("sha256").update(config.configFile).digest("hex").slice(0, 12)}`;
  const name = `pi-communication${suffix}.service`;
  return { name, path: join(home, ".config/systemd/user", name) };
}

export function renderUnit(config, { node = process.execPath, entry = cliPath } = {}) {
  if (!config.pi) throw new Error("Servizio systemd: configurazione pi richiesta");
  return `# Generated by pi-communication; configuration: ${JSON.stringify(config.configFile)}
[Unit]
Description=Pi communication - Telegram

[Service]
Type=simple
WorkingDirectory=${workingPath(config.pi.workingDirectory)}
ExecStart=:${quote(node)} ${quote(entry)} start --foreground --config ${quote(config.configFile)}
Restart=no
TimeoutStopSec=30
SendSIGKILL=no
UMask=0077
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=default.target
`;
}

export async function installedUnit(config, options = {}) {
  if ((options.platform ?? process.platform) !== "linux") return undefined;
  const unit = unitLocation(config, options);
  let content;
  try { content = await readFile(unit.path, "utf8"); }
  catch (error) { if (error.code === "ENOENT") return undefined; throw new Error("Servizio systemd: unità non leggibile"); }
  const expected = renderUnit(config, options);
  const marker = expected.split("\n")[0];
  const exec = expected.split("\n").find((line) => line.startsWith("ExecStart="));
  if (content.split("\n")[0] !== marker || !content.split("\n").includes(exec)) {
    throw new Error("Servizio systemd: unità esistente non riconosciuta; nessuna modifica o azione effettuata");
  }
  return unit;
}

/** Crea e abilita, ma non avvia. Nessuna chiamata sudo/loginctl enable-linger. */
export async function installSystemd(config, options = {}) {
  if ((options.platform ?? process.platform) !== "linux") return { supported: false };
  const run = options.run ?? runSystemCommand;
  const unit = unitLocation(config, options);
  const content = renderUnit(config, options);
  let existing;
  try { existing = await readFile(unit.path, "utf8"); }
  catch (error) { if (error.code !== "ENOENT") throw new Error("Servizio systemd: unità non leggibile"); }
  if (existing !== undefined && existing !== content) throw new Error("Servizio systemd: unità già esistente e differente; nessuna sovrascrittura");
  await mkdir(dirname(unit.path), { recursive: true, mode: 0o700 });
  if (existing === undefined) {
    const handle = await open(unit.path, "wx", 0o600);
    try { await handle.writeFile(content); }
    catch { await rm(unit.path, { force: true }); throw new Error("Servizio systemd: scrittura unità fallita"); }
    finally { await handle.close(); }
  }
  // In caso di fallimento l'unità resta disponibile per riprovare il setup.
  await run("systemctl", ["--user", "daemon-reload"]);
  await run("systemctl", ["--user", "enable", unit.name]);
  const username = options.username ?? userInfo().username;
  let linger = "unknown";
  try {
    const answer = await run("loginctl", ["show-user", username, "--property=Linger", "--value"]);
    if (["yes", "no"].includes(answer)) linger = answer;
  } catch {}
  return { supported: true, ...unit, linger, username };
}

export async function systemdStatus(config, options = {}) {
  const unit = await installedUnit(config, options);
  if (!unit) return undefined;
  const run = options.run ?? runSystemCommand;
  const answer = await run("systemctl", ["--user", "show", unit.name, "--property=ActiveState,SubState,UnitFileState,FragmentPath"]);
  const values = Object.fromEntries(answer.split("\n").map((line) => {
    const index = line.indexOf("=");
    return [line.slice(0, index), line.slice(index + 1)];
  }));
  let fragment;
  try { fragment = await realpath(values.FragmentPath); }
  catch { throw new Error("Servizio systemd: unità non caricata; ripetere setup"); }
  if (fragment !== await realpath(unit.path)) throw new Error("Servizio systemd: unità caricata diversa; nessuna azione effettuata");
  return { ...unit, active: values.ActiveState, sub: values.SubState, enabled: values.UnitFileState };
}

export async function controlSystemd(config, action, options = {}) {
  if (!["start", "stop"].includes(action)) throw new Error("Servizio systemd: azione non valida");
  const status = await systemdStatus(config, options);
  if (!status) throw new Error("Servizio systemd: unità non installata");
  await (options.run ?? runSystemCommand)("systemctl", ["--user", action, status.name]);
  return systemdStatus(config, options);
}
